"""add_email_note_to_orders

Revision ID: acf0cdc6a26b
Revises: ed0dfa3d0d32
Create Date: 2026-06-13 20:14:28.615272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf0cdc6a26b'
down_revision: Union[str, None] = 'ed0dfa3d0d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email_note', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'email_note')
    # ### end Alembic commands ###
